FILES = top.sv env.sv scoreboard.sv transaction.sv DUTout.sv generator.sv coverage.sv interface.sv driver.sv monitor.sv test.sv adder.v alu_inout_stage.v alu_output_stage.v calc2_top.v holdreg.v mux_out.v priority.v shifter.v 

TOPLEVEL = top
